POST  http://127.0.0.1:8080/auth/register
Content-Type: application/json

{
  "password": "123456",
  "email": "meuemail@gmail.com"
 
}

### Login com usuario e senha
POST  http://127.0.0.1:8080/auth/
Content-Type: application/json


{
  "login": "meuemail@gmail.com",
  "social_login": false ,
  
  "supplier_user": false,
  
  
  "password": "123456"
  }

### Login com facebook
POST  http://127.0.0.1:8080/auth/
Content-Type: application/json

{
  "login": "meuemail@gmail.com",
  "social_login": true ,
  "avatar": "test",
  "supplier_user": false,
  "social_key": "123456",    
  "social_type": "FACEBOOK",
  "password": ""
  }


### Confirm Login
PATCH   http://127.0.0.1:8080/auth/confirm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjM1MDg2MzYsImlhdCI6MTcyMzUwODYxNiwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjM1MDg2MTYsInN1YiI6IjI1Iiwic3VwcGxpZXIiOm51bGx9.HBEt9gb-Vd5WTlcnfEr8IRgdiiCHMm0gSmQhdT2TOpk

{
  "android_token": "123usjdflçal",
  "ios_token": ""
  }

### Refresh Token
PUT http://127.0.0.1:8080/auth/refresh
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjM1MDg2NTcsImlhdCI6MTcyMzUwODYzNywiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjM1MDg2MzcsInN1YiI6IjI1Iiwic3VwcGxpZXIiOm51bGx9.DWgC3GX9mttOk-2DwPY6yZUqoto0Y4mQbD2C4pHY_ew

{
  "refresh_token": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjUyMzY2MzcsImlhdCI6MTcyMzUwODYzNywiaXNzIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmxlSEFpT2pFM01qTTFNRGcyTlRjc0ltbGhkQ0k2TVRjeU16VXdPRFl6Tnl3aWFYTnpJam9pWTNWcFpHRndaWFFpTENKdVltWWlPakUzTWpNMU1EZzJNemNzSW5OMVlpSTZJakkxSWl3aWMzVndjR3hwWlhJaU9tNTFiR3g5LkRXZ0MzR1g5bXR0T2stMkR3UFk2eVpVcW90bzBZNG1RYkQyQzRwSFlfZXciLCJzdWIiOiJyZWZyZXNoVG9rZW4ifQ.h41CdcmHSNVB0VjVTucnLH1o0YLN5jHj5d7ZxkKw5wY"
}

### Pegar usuaro por token

GET http://127.0.0.1:8080/user/
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzM3NTcyMTAsImlhdCI6MTczMzY3MDgxMCwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MzM2NzA4MTAsInN1YiI6IjQxIiwic3VwcGxpZXIiOm51bGx9.slU50wHlzSo0MkT1DYD37CUd-1ATcyqsAxPLZj_BIJ0

### Atualizar avatar

PUT http://127.0.0.1:8080/user/avatar
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjM5ODY4NzUsImlhdCI6MTcyMzkwMDQ3NSwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjM5MDA0NzUsInN1YiI6IjI1Iiwic3VwcGxpZXIiOm51bGx9.jEdQ-nSMnwdFrBqf4QjVS_i_u3hOJF44BlMaaxlEe7k

{
  "url_avatar": "test"
}

### Atualizar avattokenar

PUT http://127.0.0.1:8080/user/device
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjQwMTg3MjMsImlhdCI6MTcyMzkzMjMyMywiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjM5MzIzMjMsInN1YiI6IjI1Iiwic3VwcGxpZXIiOm51bGx9.hTOmo7ew-tnZlgSFModt0J979CJSj69I2VGYhScL5Ow

{
  "token": "IOS_UPDATE_TOKEN",
  "platform": "IOS"
}

### Categprias

GET http://127.0.0.1:8080/categories/
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjM5NDM4NTEsImlhdCI6MTcyMzg1NzQ1MSwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjM4NTc0NTEsInN1YiI6IjI1Iiwic3VwcGxpZXIiOm51bGx9.Xzzfl2DWgpulOou_tJSy3ULaNz7tKNgTaQFZyEiCOv8

### Forncedores pro geo localizacao

GET http://127.0.0.1:8080/suppliers/?lat=-23.561472512749365&&lng= -46.65636555396984
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjM5NDM4NTEsImlhdCI6MTcyMzg1NzQ1MSwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjM4NTc0NTEsInN1YiI6IjI1Iiwic3VwcGxpZXIiOm51bGx9.Xzzfl2DWgpulOou_tJSy3ULaNz7tKNgTaQFZyEiCOv8

### Forncedores pro codigo

GET http://127.0.0.1:8080/suppliers/22
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjM5NDM4NTEsImlhdCI6MTcyMzg1NzQ1MSwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjM4NTc0NTEsInN1YiI6IjI1Iiwic3VwcGxpZXIiOm51bGx9.Xzzfl2DWgpulOou_tJSy3ULaNz7tKNgTaQFZyEiCOv8


### Serviço Forncedor 
GET http://127.0.0.1:8080/suppliers/2/services
Content-Type: application/json
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjM5NDM4NTEsImlhdCI6MTcyMzg1NzQ1MSwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjM4NTc0NTEsInN1YiI6IjI1Iiwic3VwcGxpZXIiOm51bGx9.Xzzfl2DWgpulOou_tJSy3ULaNz7tKNgTaQFZyEiCOv8

### Checar se o email do fornecedor ja existe 
GET http://127.0.0.1:8080/suppliers/user?email=clinicacentralabc@gmail.com
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjM5NDM4NTEsImlhdCI6MTcyMzg1NzQ1MSwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjM4NTc0NTEsInN1YiI6IjI1Iiwic3VwcGxpZXIiOm51bGx9.Xzzfl2DWgpulOou_tJSy3ULaNz7tKNgTaQFZyEiCOv8

### Checar se o email do fornecedor ja existe 
POST  http://127.0.0.1:8080/suppliers/user
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjM5NDM4NTEsImlhdCI6MTcyMzg1NzQ1MSwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjM4NTc0NTEsInN1YiI6IjI1Iiwic3VwcGxpZXIiOm51bGx9.Xzzfl2DWgpulOou_tJSy3ULaNz7tKNgTaQFZyEiCOv8

{
  "supplierName": "novo fornecedor",
  "email": "vaidacerto@gmail.com.br",
  "password": "123456",
  "category_id": 3

}

### Atualizar dados do fornecedor
PUT  http://127.0.0.1:8080/suppliers/
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjQ5Nzg3MTksImlhdCI6MTcyNDg5MjMxOSwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjQ4OTIzMTksInN1YiI6IjI5Iiwic3VwcGxpZXIiOjI1fQ.FI7WXU1NTzmroprRXi7uB3iR4TIF0xo8jRTyZhbi6QA

{
  "name": "novo fornecedor",
  "email": "vaidacerto@gmail.com.br",
  "password": "123456",
  "category": 3,
  "logo": "test",
  "address": "rua teste",
  "phone": "123456789",
  "lat": -23.561472512749365,
  "lng": -46.65636555396984

}


### Login com usuario e senha fornecedor
POST  http://127.0.0.1:8080/auth/

Content-Type: application/json

{
  "login": "vaidacerto@gmail.com.br",
  "social_login": true ,
  "avatar": "test",
  "supplier_user": true,
  "social_key": "123456",    
  "social_type": "FACEBOOK",
  "password": ""
  }

### Agendar
POST  http://127.0.0.1:8080/schedules/
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU0OTExNjIsImlhdCI6MTcyNTQwNDc2MiwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjU0MDQ3NjIsInN1YiI6IjI5Iiwic3VwcGxpZXIiOjI1fQ.7_cKwcdIf1ANkH-OhOwCowia-Jaccl1xrjxs-Js10ro
Content-Type: application/json

{
 "schedule_date": "2021-06-15T10:00:00",
  "supplier_id":20,
  "services" : [52,53,54], 
  "name": "novo fornecedor",
  "pat_name": "bia"  

}


### Agendar
put  http://127.0.0.1:8080/schedules/:id/staus/:staus
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU0OTExNjIsImlhdCI6MTcyNTQwNDc2MiwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjU0MDQ3NjIsInN1YiI6IjI5Iiwic3VwcGxpZXIiOjI1fQ.7_cKwcdIf1ANkH-OhOwCowia-Jaccl1xrjxs-Js10ro


### Pegar agendamentos
GET  http://127.0.0.1:8080/schedules/
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU0OTExNjIsImlhdCI6MTcyNTQwNDc2MiwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjU0MDQ3NjIsInN1YiI6IjI5Iiwic3VwcGxpZXIiOjI1fQ.7_cKwcdIf1ANkH-OhOwCowia-Jaccl1xrjxs-Js10ro
Content-Type: application/json

### Pegar agendamentos
GET  http://127.0.0.1:8080/schedules/supplier
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU0OTExNjIsImlhdCI6MTcyNTQwNDc2MiwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjU0MDQ3NjIsInN1YiI6IjI5Iiwic3VwcGxpZXIiOjI1fQ.7_cKwcdIf1ANkH-OhOwCowia-Jaccl1xrjxs-Js10ro
Content-Type: application/json


### Inciar chat
POST  http://127.0.0.1:8080/chats/schedule/5/start-chat
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU0OTExNjIsImlhdCI6MTcyNTQwNDc2MiwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjU0MDQ3NjIsInN1YiI6IjI5Iiwic3VwcGxpZXIiOjI1fQ.7_cKwcdIf1ANkH-OhOwCowia-Jaccl1xrjxs-Js10ro
Content-Type: application/json

###
GET  http://127.0.0.1:8080/chats/user
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU0OTExNjIsImlhdCI6MTcyNTQwNDc2MiwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjU0MDQ3NjIsInN1YiI6IjI5Iiwic3VwcGxpZXIiOjI1fQ.7_cKwcdIf1ANkH-OhOwCowia-Jaccl1xrjxs-Js10ro
Content-Type: application/json

###
GET  http://127.0.0.1:8080/chats/supplier
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU0OTExNjIsImlhdCI6MTcyNTQwNDc2MiwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjU0MDQ3NjIsInN1YiI6IjI5Iiwic3VwcGxpZXIiOjI1fQ.7_cKwcdIf1ANkH-OhOwCowia-Jaccl1xrjxs-Js10ro
Content-Type: application/json


### finalizar chat
PUT  http://127.0.0.1:8080/chats/1/end-chat
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU0OTExNjIsImlhdCI6MTcyNTQwNDc2MiwiaXNzIjoiY3VpZGFwZXQiLCJuYmYiOjE3MjU0MDQ3NjIsInN1YiI6IjI5Iiwic3VwcGxpZXIiOjI1fQ.7_cKwcdIf1ANkH-OhOwCowia-Jaccl1xrjxs-Js10ro
Content-Type: application/json